<?php require_once __DIR__.'/_common.php'; require_admin(); $d=load_data(); $s=$d['site']; $tab=$_GET['tab']??'dashboard'; $notice='';
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf(); $action=$_POST['action']??'';
 if($action==='toggle_intro'){ $d['site']['show_intro']=!$d['site']['show_intro']; save_data($d); $notice='LİG BAŞI intro '.($d['site']['show_intro']?'açıldı.':'kapatıldı.'); }
 if($action==='site'){foreach(['name','tagline','description','email','phone','address','game_status','game_url','seo_title','seo_description','hero_title','hero_text','hero_kicker'] as $k)$d['site'][$k]=trim($_POST[$k]??'');$d['site']['maintenance']=isset($_POST['maintenance']);$d['site']['show_intro']=isset($_POST['show_intro']);save_data($d);$notice='Site ayarları kaydedildi.';}
 if($action==='game'){
  foreach(['game_status','game_url','windows_url','android_url','windows_status','android_status','mac_status','apple_status','game_beta_label'] as $k)$d['site'][$k]=trim($_POST[$k]??'');
  $d['site']['game_beta_enabled']=isset($_POST['game_beta_enabled']);
  $d['site']['game_beta_progress']=max(0,min(100,(int)($_POST['game_beta_progress']??35)));
  $d['site']['show_intro']=isset($_POST['show_intro']);
  save_data($d);$notice='Lig Başı yayın ayarları güncellendi.';
 }
 if($action==='stats'){foreach(['projects','deliveries','uptime','experience'] as $k)$d['stats'][$k]=trim($_POST[$k]??'');save_data($d);$notice='İstatistikler güncellendi.';}
 if($action==='password'){if(!password_verify($_POST['current']??'',current_password_hash()))$notice='Mevcut şifre hatalı.';elseif(strlen($_POST['new']??'')<8)$notice='Yeni şifre en az 8 karakter olmalı.';elseif(($_POST['new']??'')!==($_POST['again']??''))$notice='Yeni şifreler eşleşmiyor.';else{set_admin_password($_POST['new']);$notice='Şifre değiştirildi.';}}
 if($action==='message_read'){foreach($d['messages'] as &$m)if($m['id']===$_POST['id'])$m['read']=true;save_data($d);}
 if($action==='message_delete'){$d['messages']=array_values(array_filter($d['messages'],fn($m)=>$m['id']!==$_POST['id']));save_data($d);}
 if($action==='coming_save'){$id=trim($_POST['id']??'');if($id!==''){if(!isset($d['coming_projects']))$d['coming_projects']=[];$p=['id'=>$id,'name'=>trim($_POST['name']??''),'category'=>trim($_POST['category']??''),'description'=>trim($_POST['description']??''),'status'=>trim($_POST['status']??'Çok Yakında'),'progress'=>max(0,min(100,(int)($_POST['progress']??0))),'platform'=>trim($_POST['platform']??''),'technology'=>trim($_POST['technology']??''),'enabled'=>isset($_POST['enabled']),'show_in_projects'=>isset($_POST['show_in_projects']),'url'=>trim($_POST['url']??'#'),'image'=>trim($_POST['image']??'')];$found=false;foreach($d['coming_projects'] as &$old)if($old['id']===$id){$old=$p;$found=true;}if(!$found)$d['coming_projects'][]=$p;save_data($d);$notice='Yakında proje ayarları kaydedildi.';}}
 if($action==='project_save'){$p=['id'=>trim($_POST['id']??bin2hex(random_bytes(4))),'name'=>trim($_POST['name']??''),'category'=>trim($_POST['category']??''),'description'=>trim($_POST['description']??''),'status'=>trim($_POST['status']??''),'featured'=>isset($_POST['featured']),'url'=>trim($_POST['url']??'#'),'image'=>trim($_POST['image']??'')];$found=false;foreach($d['projects'] as &$old)if($old['id']===$p['id']){$old=$p;$found=true;}if(!$found)$d['projects'][]=$p;save_data($d);$notice='Proje kaydedildi.';}
 if($action==='project_delete'){$d['projects']=array_values(array_filter($d['projects'],fn($p)=>$p['id']!==$_POST['id']));save_data($d);}
 if($action==='music_upload'){$path=upload_file('music',['mp3','ogg','wav']);if($path){$d['site']['intro_music']=$path;save_data($d);$notice='Intro müziği yüklendi.';}else $notice='Müzik yüklenemedi. MP3/OGG/WAV kullan.';}
 if($action==='music_remove'){$d['site']['intro_music']='';save_data($d);$notice='Intro müziği kaldırıldı.';}
 if($action==='watcher_save'){
  $d['watcher']['status']=trim($_POST['status']??'Çok Yakında');
  $d['watcher']['progress']=max(0,min(100,(int)($_POST['progress']??15)));
  $d['watcher']['hero_kicker']=trim($_POST['hero_kicker']??'AKINCI YAZILIM · YENİ PROJE');
  $d['watcher']['hero_text']=trim($_POST['hero_text']??'');
  $d['watcher']['cover']=trim($_POST['cover']??'assets/the-watcher-cover-v2.png');
  if(!isset($d['watcher']['gallery'])) $d['watcher']['gallery']=[];
  for($i=0;$i<4;$i++){
    $d['watcher']['gallery'][$i]=[
      'image'=>trim($_POST['g'.$i.'_image']??''),
      'title'=>trim($_POST['g'.$i.'_title']??''),
      'caption'=>trim($_POST['g'.$i.'_caption']??'')
    ];
  }
  save_data($d);$notice='THE WATCHER proje merkezi güncellendi.';
 }
 if($action==='adsense_save'){
  $pub=trim($_POST['adsense_pub_id']??'');
  if(preg_match('/^ca-pub-\d{10,30}$/',$pub)){$d['site']['adsense_pub_id']=$pub;save_data($d);$notice='AdSense yayıncı kimliği kaydedildi.';}else{$notice='AdSense yayıncı kimliği formatı geçersiz.';}
 }
 if($action==='backup'){header('Content-Type: application/json');header('Content-Disposition: attachment; filename="akinci-yedek-'.date('Ymd-His').'.json"');echo json_encode($d,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);exit;}
 $d=load_data();$s=$d['site'];
}
$unread=count(array_filter($d['messages'],fn($m)=>empty($m['read'])));$visitorData=visitor_stats();$visitorDays=$visitorData['days']??[];$todayVisitors=(int)($visitorDays[date('Y-m-d')]??0);$last30Visitors=0;foreach($visitorDays as $day=>$count){if($day>=date('Y-m-d',strtotime('-29 days'))) $last30Visitors+=(int)$count;}$visitorRows=[];for($i=13;$i>=0;$i--){$day=date('Y-m-d',strtotime('-'.$i.' days'));$visitorRows[$day]=(int)($visitorDays[$day]??0);}$maxVisitors=max(1,...array_values($visitorRows));$edit=null;$comingEdit=null;if(isset($_GET['edit']))foreach($d['projects'] as $p)if($p['id']===$_GET['edit'])$edit=$p;if(isset($_GET['coming_edit']))foreach($d['coming_projects']??[] as $p)if($p['id']===$_GET['coming_edit'])$comingEdit=$p;
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Akıncı Yönetim Merkezi</title><link rel="stylesheet" href="styles.css?v=17"></head><body class="admin-body"><div class="admin-shell"><aside class="admin-side"><a class="admin-brand" href="index.php"><img src="assets/akinci-logo-white.png"><span>YÖNETİM<br><small>MERKEZİ</small></span></a><a class="side-link <?= $tab==='dashboard'?'active':''?>" href="admin.php">⌂ Genel Bakış</a><a class="side-link <?= $tab==='site'?'active':''?>" href="admin.php?tab=site">◈ Site & SEO</a><a class="side-link <?= $tab==='projects'?'active':''?>" href="admin.php?tab=projects">▣ Projeler</a><a class="side-link <?= $tab==='coming'?'active':''?>" href="admin.php?tab=coming">◫ Yakında Projeler</a><a class="side-link <?= $tab==='game'?'active':''?>" href="admin.php?tab=game">⚽ LİG BAŞI</a><a class="side-link <?= $tab==='watcher'?'active':''?>" href="admin.php?tab=watcher">👁 THE WATCHER</a><a class="side-link <?= $tab==='adsense'?'active':''?>" href="admin.php?tab=adsense">▤ AdSense</a><a class="side-link <?= $tab==='messages'?'active':''?>" href="admin.php?tab=messages">✉ Mesajlar <?php if($unread):?><b class="count"><?=$unread?></b><?php endif;?></a><a class="side-link <?= $tab==='security'?'active':''?>" href="admin.php?tab=security">🔒 Güvenlik</a><a class="side-link <?= $tab==='legal'?'active':''?>" href="admin.php?tab=legal">⚖ Yasal & KVKK</a><a class="side-link <?= $tab==='backup'?'active':''?>" href="admin.php?tab=backup">↥ Yedek & Sistem</a><div class="side-bottom"><a href="index.php">Siteyi görüntüle ↗</a><a href="logout.php">Çıkış yap</a></div></aside><main class="admin-main"><div class="admin-top"><div><p class="eyebrow">AKINCI YAZILIM</p><h1><?php $titles=['dashboard'=>'Yönetim merkezi','site'=>'Site & SEO','projects'=>'Projeler','coming'=>'Yakında Projeler','game'=>'LİG BAŞI yayın merkezi','watcher'=>'THE WATCHER proje merkezi','adsense'=>'AdSense & doğrulama','messages'=>'Mesajlar','security'=>'Güvenlik','legal'=>'Yasal & KVKK','backup'=>'Yedek & Sistem'];echo $titles[$tab]??'Yönetim merkezi';?></h1></div><span class="status-pill">● Sistem aktif</span></div><?php if($notice):?><div class="alert success"><?=e($notice)?></div><?php endif;?>
<?php if($tab==='dashboard'):?>
<div class="admin-cards">
<div><span>MESAJLAR</span><strong><?=$unread?></strong><small>Okunmamış</small></div>
<div><span>PROJELER</span><strong><?=count($d['projects'])?></strong><small>Yönetilen</small></div>
<div><span>OYUN DURUMU</span><strong><?=e($s['game_status'])?></strong><small>LİG BAŞI</small></div>
<div><span>INTRO</span><strong><?= $s['show_intro']?'AÇIK':'KAPALI'?></strong><small>Video modalı · <a href="admin.php?tab=game"><?= $s['show_intro']?'Kapat':'Aç'?></a></small></div>
<div><span>THE WATCHER</span><strong><?=e((string)($d['watcher']['progress']??15))?>%</strong><small><?=e($d['watcher']['status']??'Çok Yakında')?> · <a href="admin.php?tab=watcher">Yönet</a></small></div>
<div><span>ADSENSE</span><strong>HAZIR</strong><small>Publisher ID · <a href="admin.php?tab=adsense">Kontrol</a></small></div>
</div>
<div class="admin-grid2">
<section class="panel visitor-panel">
  <div class="panel-head"><div><h2>Ziyaretçi istatistikleri</h2><p class="muted">Günlük benzersiz ziyaretçi · son 14 gün</p></div><div class="visitor-total"><b><?=$todayVisitors?></b><span>BUGÜN</span></div></div>
  <div class="visitor-chart">
  <?php foreach($visitorRows as $day=>$count): $h=$maxVisitors?max(4,round(($count/$maxVisitors)*150)):4; ?><div class="visitor-day"><div class="visitor-bar-wrap"><i style="height:<?=$h?>px" title="<?=e($day)?>: <?=$count?> ziyaretçi"></i></div><b><?=$count?></b><span><?=e(date('d.m',strtotime($day)))?></span></div><?php endforeach; ?>
  </div>
  <div class="visitor-summary"><div><b><?=$todayVisitors?></b><span>Bugün</span></div><div><b><?=$last30Visitors?></b><span>Son 30 gün</span></div><div><b><?=array_sum($visitorRows)?></b><span>Son 14 gün</span></div></div>
  <p class="muted visitor-note">Sayım çerez üzerinden günlük benzersiz tarayıcıları ölçer; IP adresi kaydedilmez.</p>
</section>
<section class="panel">
<h2>Hızlı yayın kontrolü</h2><p class="muted">LİG BAŞI'nı ve intro durumunu buradan hızlıca kontrol et.</p>
<div class="quick"><a href="admin.php?tab=game">LİG BAŞI ayarları →</a><a href="admin.php?tab=watcher">THE WATCHER merkezi →</a><a href="admin.php?tab=adsense">AdSense kontrolü →</a><form method="post" class="inline"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="toggle_intro"><button class="quick-button"><?= $s['show_intro']?'İntroyu kapat →':'İntroyu aç →'?></button></form><a href="admin.php?tab=messages">Mesajları aç →</a></div>
</section>
</div>
<section class="panel recent-visitors"><div class="panel-head"><div><h2>Gün gün ziyaretçi sayısı</h2><p class="muted">Bugün dahil son 14 günün özeti.</p></div></div><div class="visitor-table"><div class="visitor-table-head"><span>Tarih</span><span>Gün</span><span>Ziyaretçi</span></div><?php foreach(array_reverse($visitorRows,true) as $day=>$count): ?><div><span><?=e(date('d.m.Y',strtotime($day)))?></span><span><?=e(['Pazar','Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'][date('w',strtotime($day))])?></span><b><?=e((string)$count)?></b></div><?php endforeach; ?></div></section>
<?php elseif($tab==='site'):?><form method="post" class="panel form-panel"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="site"><h2>Marka ve ana sayfa</h2><div class="form-grid"><?php foreach(['name'=>'Site adı','tagline'=>'Kısa slogan','email'=>'E-posta','phone'=>'Telefon','address'=>'Adres','hero_kicker'=>'Hero üst başlık','hero_title'=>'Hero başlık','hero_text'=>'Hero açıklama','seo_title'=>'SEO başlığı','seo_description'=>'SEO açıklaması'] as $k=>$label):?><label><?=$label?><input name="<?=$k?>" value="<?=e($s[$k])?>"></label><?php endforeach;?></div><label>Kurumsal açıklama<textarea name="description"><?=e($s['description'])?></textarea></label><div class="toggle-row"><label><input type="checkbox" name="maintenance" <?=$s['maintenance']?'checked':''?>> Bakım modu</label><label><input type="checkbox" name="show_intro" <?=$s['show_intro']?'checked':''?>> LİG BAŞI intro aktif</label></div><button class="btn primary">Ayarları kaydet</button></form>
<?php elseif($tab==='projects'):?><section class="panel"><div class="panel-head"><div><h2>Projeler</h2><p class="muted">Ana sayfadaki proje kartlarını buradan yönet.</p></div><a class="btn primary" href="admin.php?tab=projects&edit=new">+ Yeni proje</a></div><?php foreach($d['projects'] as $p):?><div class="project-admin"><div><b><?=e($p['name'])?></b><span><?=e($p['category'])?> · <?=e($p['status'])?></span></div><div><a class="small-btn" href="admin.php?tab=projects&edit=<?=e($p['id'])?>">Düzenle</a><form method="post" class="inline"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="project_delete"><input type="hidden" name="id" value="<?=e($p['id'])?>"><button class="small-btn danger-text">Sil</button></form></div></div><?php endforeach;?></section><?php if($edit||isset($_GET['edit'])):$p=$edit?:['id'=>'','name'=>'','category'=>'','description'=>'','status'=>'Geliştiriliyor','featured'=>false,'url'=>'#','image'=>''];?><form method="post" class="panel form-panel"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="project_save"><div class="form-grid"><label>ID<input name="id" value="<?=e($p['id'])?>" required></label><label>Proje adı<input name="name" value="<?=e($p['name'])?>" required></label><label>Kategori<input name="category" value="<?=e($p['category'])?>"></label><label>Durum<input name="status" value="<?=e($p['status'])?>"></label><label>Bağlantı<input name="url" value="<?=e($p['url'])?>"></label><label>Görsel yolu<input name="image" value="<?=e($p['image'])?>"></label></div><label>Açıklama<textarea name="description"><?=e($p['description'])?></textarea></label><label><input type="checkbox" name="featured" <?=$p['featured']?'checked':''?>> Ana sayfada göster</label><button class="btn primary">Projeyi kaydet</button></form><?php endif;?>
<?php elseif($tab==='coming'):?>
<section class="panel"><div class="panel-head"><div><h2>Yakında projeler</h2><p class="muted">C# / .NET projelerini ana sayfada ve kendi ürün sayfalarında ayrı ayrı yönet.</p></div></div>
<?php foreach(($d['coming_projects']??[]) as $cp): ?><div class="project-admin coming-admin-row"><div><b><?=e($cp['name'])?></b><span><?=e($cp['status'])?> · %<?=e((string)($cp['progress']??0))?> · <?=e($cp['technology']??'')?></span></div><div><a class="small-btn" href="admin.php?tab=coming&coming_edit=<?=e($cp['id'])?>">Detaylı düzenle</a></div></div><?php endforeach; ?>
</section>
<?php if($comingEdit || isset($_GET['coming_edit'])):$cp=$comingEdit?:['id'=>'','name'=>'','category'=>'Kurumsal Yazılım','description'=>'','status'=>'Çok Yakında','progress'=>0,'platform'=>'Windows','technology'=>'C# / .NET','enabled'=>true,'show_in_projects'=>true,'url'=>'#','image'=>'']; ?>
<form method="post" class="panel form-panel"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="coming_save"><h2><?=e($cp['name']?:'Yeni yakında proje')?> kontrolü</h2><p class="muted">Durum, ilerleme, platform, teknoloji, ürün sayfası ve ana sayfadaki görünürlüğü buradan kontrol edebilirsin.</p><div class="form-grid"><label>ID<input name="id" value="<?=e($cp['id'])?>" required></label><label>Proje adı<input name="name" value="<?=e($cp['name'])?>" required></label><label>Kategori<input name="category" value="<?=e($cp['category'])?>"></label><label>Durum<input name="status" value="<?=e($cp['status'])?>" placeholder="Çok Yakında / Beta / Yayında"></label><label>İlerleme %<input type="number" name="progress" min="0" max="100" value="<?=e((string)($cp['progress']??0))?>"></label><label>Platform<input name="platform" value="<?=e($cp['platform']??'Windows')?>"></label><label>Teknoloji<input name="technology" value="<?=e($cp['technology']??'C# / .NET')?>"></label><label>Ürün sayfası<input name="url" value="<?=e($cp['url']??'#')?>"></label><label>Görsel yolu<input name="image" value="<?=e($cp['image']??'')?>"></label></div><label>Açıklama<textarea name="description"><?=e($cp['description'])?></textarea></label><div class="toggle-row"><label><input type="checkbox" name="enabled" <?=!empty($cp['enabled'])?'checked':''?>> Proje aktif</label><label><input type="checkbox" name="show_in_projects" <?=!empty($cp['show_in_projects'])?'checked':''?>> Projeler bölümünde göster</label></div><button class="btn primary">Yakında projeyi kaydet</button></form><?php endif;?>
<?php elseif($tab==='game'):?>
<form method="post" class="panel form-panel">
<input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="game">
<h2>Lig Başı yayın merkezi</h2><p class="muted">Oyunun yayın durumunu, beta ilerlemesini ve Windows / Android indirme bağlantılarını buradan yönet.</p>
<div class="form-grid">
<label>Oyun durumu<input name="game_status" value="<?=e($s['game_status']??'Geliştiriliyor')?>"></label>
<label>Windows durumu<input name="windows_status" value="<?=e($s['windows_status']??'Çok Yakında')?>"></label>
<label>Android durumu<input name="android_status" value="<?=e($s['android_status']??'Çok Yakında')?>"></label>
<label>Mac durumu<input name="mac_status" value="<?=e($s['mac_status']??'Bekleniyor')?>"></label>
<label>Apple durumu<input name="apple_status" value="<?=e($s['apple_status']??'Bekleniyor')?>"></label>
<label>Windows indirme bağlantısı<input name="windows_url" value="<?=e($s['windows_url']??'')?>" placeholder="https://..."></label>
<label>Android indirme bağlantısı<input name="android_url" value="<?=e($s['android_url']??'')?>" placeholder="https://..."></label>
<label>Oyun / Web URL<input name="game_url" value="<?=e($s['game_url']??'')?>" placeholder="https://..."></label>
<label>Beta başlığı<input name="game_beta_label" value="<?=e($s['game_beta_label']??'Geliştirme aşamasında')?>"></label>
<label>Beta ilerleme yüzdesi<input type="number" name="game_beta_progress" min="0" max="100" value="<?=e((string)($s['game_beta_progress']??35))?>"></label>
</div>
<div class="toggle-row"><label><input type="checkbox" name="game_beta_enabled" <?=!empty($s['game_beta_enabled'])?'checked':''?>> Beta / geliştirme çubuğunu göster</label><label><input type="checkbox" name="show_intro" <?=$s['show_intro']?'checked':''?>> Lig Başı intro aktif</label></div>
<p class="muted">Windows veya Android bağlantısı girildiğinde ilgili kart otomatik olarak <b>İNDİR</b> butonuna dönüşür ve girilen bağlantıyı yeni sekmede açar. Bağlantı boşsa durum metni gösterilir.</p>
<button class="btn primary">Yayın ayarlarını kaydet</button>
</form>
<section class="panel form-panel"><h2>Intro müziği</h2><p class="muted">MP3, OGG veya WAV yükle. Intro açıldığında video ile birlikte çalar.</p><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="music_upload"><input type="file" name="music" accept="audio/mpeg,audio/ogg,audio/wav,.mp3,.ogg,.wav" required><button class="btn primary">Müziği yükle</button></form><?php if($s['intro_music']):?><div class="current-media">Aktif müzik: <code><?=e($s['intro_music'])?></code><form method="post" class="inline"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="music_remove"><button class="small-btn danger-text">Kaldır</button></form></div><?php endif;?></section>
<?php elseif($tab==='adsense'):?>
<section class="panel form-panel adsense-panel"><div class="feature-heading"><div><span class="feature-kicker">MONETİZASYON</span><h2>Google AdSense</h2><p class="muted">AdSense doğrulama kodu sitenin ortak head bölümüne eklenmiş durumda. Buradan yayıncı kimliğini ve kontrol adımlarını yönet.</p></div><div class="adsense-live"><b>AKTİF</b><span>Global head snippet</span></div></div>
<form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="adsense_save"><label>AdSense yayıncı kimliği<input name="adsense_pub_id" value="<?=e($s['adsense_pub_id']??'ca-pub-1786600436043474')?>" pattern="ca-pub-[0-9]{10,30}" required></label><div class="adsense-code"><span>HEAD SNIPPET</span><code>&lt;script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=<?=e($s['adsense_pub_id']??'ca-pub-1786600436043474')?>" crossorigin="anonymous"&gt;&lt;/script&gt;</code></div><button class="btn primary">AdSense kimliğini kaydet</button></form></section>
<section class="panel"><div class="panel-head"><div><h2>Doğrulama kontrolü</h2><p class="muted">AdSense ekranında “Doğrula” düğmesine basmadan önce bunları kontrol et.</p></div></div><div class="adsense-checks"><div><b>01</b><span><strong>Site head</strong> Ortak <?=e('adsense_head()')?> kodu yükleniyor.</span></div><div><b>02</b><span><strong>ads.txt</strong> Kök dizindeki dosya publisher kimliğini taşıyor.</span></div><div><b>03</b><span><strong>Yayıncı ID</strong> <?=e($s['adsense_pub_id']??'ca-pub-1786600436043474')?></span></div><div><b>04</b><span><strong>Son adım</strong> AdSense → Site sahibi olduğunuzu doğrulayın → Doğrula.</span></div></div></section>
<?php elseif($tab==='messages'):?><section class="panel"><h2>Gelen mesajlar</h2><?php foreach(array_reverse($d['messages']) as $m):?><article class="message <?=empty($m['read'])?'unread':''?>"><div class="message-head"><div><b><?=e($m['name'])?></b><span><?=e($m['email'])?></span></div><small><?=e($m['date'])?></small></div><h3><?=e($m['subject']?:'Genel iletişim')?></h3><p><?=nl2br(e($m['message']))?></p><div class="message-actions"><?php if(empty($m['read'])):?><form method="post" class="inline"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="message_read"><input type="hidden" name="id" value="<?=e($m['id'])?>"><button class="small-btn">Okundu</button></form><?php endif;?><form method="post" class="inline"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="message_delete"><input type="hidden" name="id" value="<?=e($m['id'])?>"><button class="small-btn danger-text">Sil</button></form></div></article><?php endforeach;if(!$d['messages'])echo '<p class="muted">Henüz mesaj yok.</p>';?></section>
<?php elseif($tab==='watcher'):?>
<section class="panel form-panel admin-feature-panel"><div class="feature-heading"><div><span class="feature-kicker">PROJE KONTROL MERKEZİ</span><h2>THE WATCHER</h2><p class="muted">Ana görsel, tanıtım metni, ilerleme yüzdesi ve 4 adet galeri görselini tek ekrandan yönet.</p></div><div class="feature-status"><strong><?=e((string)($d['watcher']['progress']??15))?>%</strong><span><?=e($d['watcher']['status']??'Çok Yakında')?></span></div></div>
<form method="post" class="watcher-admin-form"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="watcher_save">
<div class="form-grid"><label>Durum<input name="status" value="<?=e($d['watcher']['status']??'Çok Yakında')?>"></label><label>İlerleme %<input type="number" min="0" max="100" name="progress" value="<?=e((string)($d['watcher']['progress']??15))?>"></label><label class="span-2">Hero üst başlık<input name="hero_kicker" value="<?=e($d['watcher']['hero_kicker']??'AKINCI YAZILIM · YENİ PROJE')?>"></label></div>
<label>Tanıtım metni<textarea name="hero_text"><?=e($d['watcher']['hero_text']??'')?></textarea></label>
<div class="asset-highlight"><div><b>ANA GÖRSEL</b><span>Yeni cache-bust edilmiş dosya kullanılıyor.</span></div><input name="cover" value="<?=e($d['watcher']['cover']??'assets/the-watcher-cover-v2.png')?>"></div>
<div class="watcher-admin-gallery"><h3>Galeri / Oyun dünyası</h3><div class="watcher-admin-grid"><?php foreach(($d['watcher']['gallery']??[]) as $i=>$g): ?><div class="watcher-admin-card"><span class="gallery-index">0<?=($i+1)?></span><label>Görsel yolu<input name="g<?=$i?>_image" value="<?=e($g['image']??'')?>"></label><label>Başlık<input name="g<?=$i?>_title" value="<?=e($g['title']??'')?>"></label><label>Açıklama<input name="g<?=$i?>_caption" value="<?=e($g['caption']??'')?>"></label></div><?php endforeach; ?></div></div>
<button class="btn primary">THE WATCHER ayarlarını kaydet</button></form></section>
<section class="panel"><div class="panel-head"><div><h2>Yayın kontrol listesi</h2><p class="muted">Görselin doğru projeye bağlı olduğunu hızlıca kontrol et.</p></div></div><div class="watcher-checks"><div><b>✓</b><span>THE WATCHER ana görseli: <code><?=e($d['watcher']['cover']??'')?></code></span></div><div><b>✓</b><span>Galeri: <?=count($d['watcher']['gallery']??[])?> görsel aktif.</span></div><div><b>✓</b><span>Sayfa: <a href="the-watcher.php" target="_blank">the-watcher.php ↗</a></span></div><div><b>✓</b><span>Lig Başı ana görselinden bağımsız dosya adı kullanılıyor.</span></div></div></section>
<?php elseif($tab==='security'):?><section class="panel form-panel"><h2>Yönetici şifresi</h2><p class="muted">Mevcut şifreyi doğrulayarak yeni bir şifre belirle.</p><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="password"><div class="form-grid"><label>Mevcut şifre<input type="password" name="current" required></label><label>Yeni şifre<input type="password" name="new" minlength="8" required></label><label>Yeni şifre tekrar<input type="password" name="again" minlength="8" required></label></div><button class="btn primary">Şifreyi güncelle</button></form></section>
<?php elseif($tab==='legal'):?>
<section class="panel form-panel legal-admin-panel"><h2>Yasal & KVKK merkezi</h2><p class="muted">Sitedeki hukuki metinlere ve yayına alma kontrol listesine buradan erişebilirsin.</p><div class="legal-admin-grid"><a class="legal-admin-card" href="kvkk.php" target="_blank"><b>KVKK &amp; Yasal Bilgilendirme ↗</b><span>Aynı sayfada KVKK Aydınlatma Metni ve Yasal Zorunluluklar sekmeleri.</span></a></div><div class="legal-checklist"><h3>Yayına almadan önce doğrula</h3><label>☐ Şirketin tam ticari unvanı ve açık adresi doğru mu?</label><label>☐ KVKK başvuru kanalı gerçek iletişim bilgileriyle tanımlı mı?</label><label>☐ Kullanılan tüm çerez ve üçüncü taraf servisler listelendi mi?</label><label>☐ Yurt dışına veri aktarımı varsa hukuki dayanak kontrol edildi mi?</label><label>☐ Ticari ileti gönderiliyorsa 6563 / İYS süreci kontrol edildi mi?</label><label>☐ Satış veya ödeme varsa tüketici ve mesafeli satış metinleri hazır mı?</label><label>☐ Görsel, müzik, video ve yazılım lisansları kontrol edildi mi?</label></div><div class="legal-warning"><b>Not:</b> Bu panel bir hukuk danışmanı yerine geçmez. Metinlerdeki yer tutucu şirket bilgileri gerçek bilgilerle değiştirilmeden “tam uyumlu” kabul edilmemelidir.</div></section>
<?php elseif($tab==='backup'):?><section class="panel form-panel"><h2>Yedek & sistem</h2><p class="muted">Site ayarlarını, projeleri ve mesajları JSON olarak indir.</p><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="action" value="backup"><button class="btn primary">JSON yedeğini indir</button></form><div class="system-list"><span>PHP</span><b><?=e(PHP_VERSION)?></b><span>Veri dosyası</span><b><?=is_writable(DATA_FILE)?'Yazılabilir':'Yazılamıyor'?></b><span>Yükleme klasörü</span><b><?=is_writable(UPLOAD_DIR)?'Yazılabilir':'Yazılamıyor'?></b></div></section><?php endif;?></main></div></body></html>
