<?php require_once __DIR__.'/_common.php'; $d=load_data(); $s=$d['site']; ?>
<!doctype html><html lang="tr"><head>
<?php if(function_exists('adsense_head')) echo adsense_head(); ?><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow"><title>KVKK & Yasal Bilgilendirme · <?=e($s['name'])?></title><link rel="stylesheet" href="styles.css?v=20"><style>
.legal-page{background:#f4f7f9;color:#14202a;min-height:100vh}.legal-wrap{max-width:1080px;margin:0 auto;padding:48px 24px 90px}.legal-top{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:30px}.legal-brand{font:800 12px/1 Manrope;letter-spacing:.22em;color:#e5232d}.legal-back{color:#14202a;text-decoration:none;border:1px solid #ccd6dd;padding:11px 15px;font-size:12px}.legal-card{background:#fff;border:1px solid #dce4e9;padding:42px;box-shadow:0 18px 50px rgba(20,32,42,.06)}.legal-card h1{font:800 clamp(34px,5vw,54px)/1.05 Manrope;margin:0 0 12px;letter-spacing:-.05em}.legal-card .lead{color:#60707b;line-height:1.8;margin:0 0 38px}.legal-card h2{font:800 21px Manrope;margin:38px 0 12px}.legal-card h3{font:700 16px Manrope;margin:26px 0 8px}.legal-card p,.legal-card li{font:15px/1.85;color:#43515b}.legal-card ul{padding-left:22px}.legal-note{padding:18px 20px;background:#f5f7f8;border-left:3px solid #e5232d;margin:24px 0}.legal-table{width:100%;border-collapse:collapse;margin:18px 0}.legal-table td{border:1px solid #dce4e9;padding:13px;vertical-align:top;font-size:14px;line-height:1.65}.legal-table td:first-child{font-weight:700;width:31%;background:#f7f9fa}.legal-foot{margin-top:28px;color:#73818a;font-size:12px;line-height:1.7}.legal-tabs{display:flex;gap:10px;margin-bottom:18px;flex-wrap:wrap}.legal-tab{appearance:none;border:1px solid #cfd9df;background:#fff;color:#34444f;padding:13px 18px;font:700 13px Manrope;cursor:pointer}.legal-tab.active{background:#e5232d;border-color:#e5232d;color:#fff}.legal-pane{display:none}.legal-pane.active{display:block}.legal-pane .pane-title{font:800 clamp(30px,4vw,46px)/1.1 Manrope;margin:0 0 10px}.req{display:grid;grid-template-columns:80px 1fr;gap:20px;padding:23px 0;border-top:1px solid #e4e9ed}.num{font:800 28px Manrope;color:#e5232d}.req h2{font:800 19px Manrope;margin:0 0 7px}.req p,.req li{font:14px/1.8;color:#4a5963}.req ul{padding-left:20px}.warn{background:#fff6f6;border:1px solid #f0cccc;padding:20px;margin:28px 0}@media(max-width:700px){.legal-card{padding:25px}.legal-top{align-items:flex-start;flex-direction:column}.legal-table td{display:block;width:auto!important}.req{grid-template-columns:1fr;gap:5px}}
</style></head><body class="legal-page"><div class="legal-wrap"><div class="legal-top"><div class="legal-brand">AKINCI YAZILIM</div><a class="legal-back" href="index.php">← Siteye dön</a></div><div class="legal-tabs" role="tablist"><button class="legal-tab active" data-tab="kvkk" type="button">KVKK Aydınlatma Metni</button><button class="legal-tab" data-tab="yasal" type="button">Yasal Zorunluluklar</button></div><article class="legal-card"><section id="pane-kvkk" class="legal-pane active">
<h1>KVKK Aydınlatma Metni</h1>
<p class="lead">Bu metin, 6698 sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) kapsamında Akıncı Yazılım internet sitesi ve LİG BAŞI uygulamaları bakımından kişisel verilerin hangi kapsamda işlenebileceğini açıklamak amacıyla hazırlanmıştır.</p>
<div class="legal-note"><b>Önemli:</b> Bu metin genel bir bilgilendirme metnidir; hukuk danışmanlığı veya somut olay için hukuki görüş değildir. Yayına alınmadan önce veri sorumlusunun gerçek ticari unvanı, açık adresi, başvuru kanalı, kullanılan barındırma/analitik/iletişim hizmetleri, veri aktarım noktaları ve gerçek saklama süreleri şirket tarafından doğrulanmalıdır.</div>

<h2>1. Veri Sorumlusu</h2>
<p>KVKK bakımından veri sorumlusu, kişisel verilerin işleme amaçlarını ve vasıtalarını belirleyen gerçek veya tüzel kişidir. Bu site bakımından aşağıdaki şirket bilgileri kullanılmaktadır; gerçek ticari bilgiler yayına alınmadan önce kesinleştirilmelidir.</p>
<table class="legal-table"><tr><td>Unvan / Ad</td><td><?=e($s['name'])?> <b>— tam ticaret unvanı kesinleştirilmelidir.</b></td></tr><tr><td>Adres</td><td><?=e($s['address'])?> <b>— açık yasal adres eklenmelidir.</b></td></tr><tr><td>E-posta</td><td><?=e($s['email'])?></td></tr><tr><td>Telefon</td><td><?=e($s['phone']?:'Şirket telefonu eklenmelidir.')?></td></tr></table>

<h2>2. Bu Site Üzerinde Hangi Veriler İşlenebilir?</h2>
<p>Verinin gerçekten işlenip işlenmediği, kullanılan özelliklere göre değişir. Sitede aşağıdaki veri kategorileri gündeme gelebilir:</p>
<ul><li><b>Kimlik bilgileri:</b> ad ve soyad gibi iletişim talebinin kurulması için kullanıcı tarafından gönderilen bilgiler.</li><li><b>İletişim bilgileri:</b> e-posta adresi, telefon numarası ve kullanıcının kendi isteğiyle verdiği diğer iletişim bilgileri.</li><li><b>Talep ve mesaj verileri:</b> konu, mesaj metni, proje açıklaması, teklif talebi ve yazışma içeriği.</li><li><b>İşlem/güvenlik verileri:</b> tarih-saat, oturum ve güvenlik açısından gerekli teknik kayıtlar.</li><li><b>Ziyaret ölçüm verileri:</b> kullanılan ölçüm mekanizmasına bağlı olarak gün bazında ziyaret/benzersiz tarayıcı sayıları gibi toplulaştırılmış istatistikler.</li><li><b>Çerez ve benzeri teknolojiler:</b> yalnızca fiilen kullanılan teknolojiler kapsamında teknik veya ölçüm verileri.</li></ul>
<p>Özel nitelikli kişisel verilerin iletişim formlarına gereksiz yere yazılmaması gerekir. Kullanıcıların sağlık, biyometrik, genetik, siyasi, dini, sendika üyeliği veya benzeri hassas bilgileri paylaşmaktan kaçınması önerilir.</p>

<h2>3. Site İletişim Formu</h2>
<p>Bu internet sitesinde kullanıcılar için <b>genel sohbet veya kullanıcılar arası mesajlaşma özelliği bulunmaz.</b> Sitedeki İletişim alanı yalnızca Akıncı Yazılım'a iletişim/teklif talebi göndermek için kullanılan bir formdur. Formda ad-soyad, e-posta, konu ve mesaj alanları bulunabilir.</p>
<h3>Mesajlar kim tarafından görülür?</h3>
<p>Gönderilen mesajlar sitenin herkese açık bölümünde yayınlanmaz. Mesaj içerikleri yalnızca yetkilendirilmiş yönetici hesabının erişebildiği <b>yalnızca yetkilendirilmiş kişiler tarafından erişilebilen kapalı yönetim alanında</b> görüntülenmek üzere saklanır. Ziyaretçiler başka kişilerin mesajlarını, e-posta adreslerini veya yönetici panelini göremez.</p>
<h3>Mesajlar hangi amaçlarla kullanılır?</h3>
<ul><li>İletişim talebini değerlendirmek ve yanıtlamak.</li><li>Teklif, proje, iş birliği veya destek talebinin yürütülmesi.</li><li>Talep geçmişinin ve iletişim sürecinin gerektiğinde takip edilmesi.</li><li>Kötüye kullanım, spam, dolandırıcılık veya güvenlik olaylarının önlenmesi.</li><li>Hukuki yükümlülüklerin yerine getirilmesi veya bir hakkın tesisi, kullanılması ya da korunması.</li></ul>
<h3>Mesajlarda ne paylaşılmamalıdır?</h3>
<p>Şifre, banka/kredi kartı bilgisi, kimlik belgesi görüntüsü, sağlık bilgisi, özel nitelikli kişisel veri veya üçüncü kişilere ait gereksiz kişisel bilgilerin gönderilmemesi gerekir. Böyle bir bilgi gönderilirse, ilgili içeriğin güvenli biçimde ele alınması ve gerekli olduğunda silinmesi değerlendirilir.</p>

<h2>4. LİG BAŞI Uygulaması İçindeki Global Sohbet</h2>
<p><b>Global sohbet yalnızca LİG BAŞI uygulamalarının içinde bulunur.</b> İnternet sitesinde bu özellik bulunmaz. Windows ve Android uygulamalarında kullanıcıların aynı ortak sohbet alanında mesajlaşabilmesi amacıyla kullanılabilir.</p>
<ul><li>Mesaj gönderebilmek için uygulama hesabıyla giriş yapılması gerekir.</li><li>Mesajlarda kullanıcı adı ve mesaj içeriği gibi veriler işlenebilir.</li><li>Mesajlar diğer uygulama kullanıcılarına görüntülenebilir; bu alan internet sitesinin herkese açık sayfalarından ayrı bir uygulama özelliğidir.</li><li>Mesaj içerikleri güvenlik, kötüye kullanımın önlenmesi, topluluk düzeninin korunması ve teknik işletim amacıyla işlenebilir.</li><li>Şifre, banka/kredi kartı bilgisi, kimlik belgesi, sağlık bilgisi veya gereksiz özel nitelikli kişisel veriler sohbet alanında paylaşılmamalıdır.</li><li>Uygulamadaki sohbet kayıtlarının saklama süresi ve gerektiğinde silinmesi, gerçek sunucu yapılandırması ve yürürlükteki mevzuata göre belirlenir.</li></ul>
<div class="legal-note"><b>Önemli ayrım:</b> Akıncı Yazılım internet sitesinde kullanıcılar arası sohbet yoktur. Global sohbet özelliği yalnızca LİG BAŞI uygulamalarında yer alır.</div>

<h2>5. Mesajların Saklanması ve Yönetimi</h2>
<p>Mesaj kayıtları, iletişim talebinin amacı için gerekli olduğu sürece ve varsa ilgili mevzuattaki saklama yükümlülükleri kadar tutulur. Amaç ortadan kalktığında veya saklama süresi sona erdiğinde, uygulanabilir mevzuata uygun olarak silme, yok etme veya anonimleştirme değerlendirilir.</p>
<p>Yönetici panelindeki mesajlar kamuya açık bir içerik alanı değildir. Yönetici erişimi; parola, oturum ve yetkilendirme kontrolleriyle sınırlandırılmalı; yönetici hesabı üçüncü kişilerle paylaşılmamalıdır.</p>

<h2>6. Kişisel Verilerin İşlenme Amaçları</h2>
<ul><li>İletişim taleplerine cevap verilmesi.</li><li>Teklif ve proje süreçlerinin yürütülmesi.</li><li>Hizmet ve ürünlerin sunulması, geliştirilmesi ve teknik olarak işletilmesi.</li><li>Bilgi güvenliğinin sağlanması, kötüye kullanım ve spam girişimlerinin önlenmesi.</li><li>Yasal yükümlülüklerin yerine getirilmesi.</li><li>Uyuşmazlıkların yönetilmesi ve hakların korunması.</li><li>Fiilen kullanılan ölçüm/istatistik araçlarıyla hizmet performansının değerlendirilmesi.</li></ul>

<h2>7. Hukuki Sebepler</h2>
<p>Her işleme faaliyeti için KVKK'nın 5. ve uygulanabildiği ölçüde 6. maddelerinde yer alan uygun işleme şartı ayrıca belirlenir. Faaliyete göre kanunda açıkça öngörülme, sözleşmenin kurulması veya ifası için gerekli olma, hukuki yükümlülüğün yerine getirilmesi, bir hakkın tesisi/kullanılması/korunması, veri sorumlusunun meşru menfaati veya şartları oluştuğunda açık rıza gibi hukuki sebepler gündeme gelebilir.</p>
<div class="legal-note"><b>Aydınlatma ≠ açık rıza:</b> KVKK kapsamında aydınlatma yükümlülüğü, veri işleme açık rızaya dayansa da başka bir kanuni işleme şartına dayansa da ayrıca yerine getirilmesi gereken bir yükümlülüktür. Aydınlatma metni ile açık rıza metni birbirinin yerine kullanılmamalıdır.</div>

<h2>8. Kişisel Verilerin Toplanma Yöntemi</h2>
<p>Veriler; internet sitesindeki iletişim formu, kullanıcı tarafından doğrudan gönderilen elektronik iletişimler, teknik sistem kayıtları ve kullanılan özelliklere göre çerez/benzeri teknolojiler aracılığıyla elektronik ortamda elde edilebilir. Kullanılan yöntemler ve veri kategorileri gerçek sistemle uyumlu tutulmalıdır.</p>

<h2>9. Verilerin Aktarılması</h2>
<p>Kişisel veriler, işleme amacıyla sınırlı ve gerekli olmak kaydıyla; barındırma/altyapı sağlayıcıları, e-posta veya iletişim hizmet sağlayıcıları, teknik destek sağlayıcıları, yetkili kamu kurum ve kuruluşları veya hukuken yetkili diğer alıcı gruplarına aktarılabilir. Fiilen kullanılmayan bir hizmet sağlayıcı veya alıcı grubu bu metne eklenmemelidir.</p>
<p>Yurt dışına veri aktarımı yapılması halinde, KVKK'nın güncel yurt dışı aktarım hükümleri, uygun güvence mekanizmaları ve gerekli şartlar ayrıca değerlendirilir.</p>

<h2>10. Çerezler ve Ziyaret İstatistikleri</h2>
<p>Site, teknik işlevlerin sağlanması veya ziyaret ölçümünün yapılması amacıyla çerez ya da benzeri teknolojiler kullanabilir. Kullanılan her teknoloji için adı, sağlayıcısı, amacı, süresi ve hukuki dayanağı gerçek uygulamaya göre ayrıca belirlenmelidir.</p>
<p>İstatistik özelliği kullanıldığında toplulaştırılmış günlük ziyaret sayıları gibi bilgiler yönetici panelinde gösterilebilir. Bu tür istatistiklerin kamuya açık şekilde paylaşılması amaçlanmaz. IP adresi gibi kişisel verilerin işlenip işlenmediği kullanılan gerçek altyapıya göre ayrıca değerlendirilmelidir.</p>

<h2>11. Veri Güvenliği ve Yetki Kontrolü</h2>
<p>Veri sorumlusu, kişisel verilerin hukuka aykırı işlenmesini ve erişilmesini önlemek ve güvenli biçimde muhafazasını sağlamak için uygun teknik ve idari tedbirleri almakla yükümlüdür. Bu kapsamda yetkisiz yönetici erişiminin önlenmesi, güçlü parola, güvenli bağlantı, güncel yazılım, erişim yetkilerinin sınırlandırılması, yedekleme ve olay yönetimi gibi kontroller işleme faaliyetinin niteliğine göre uygulanmalıdır.</p>

<h2>12. Veri Minimizasyonu</h2>
<p>Site formlarında hizmetin amacı için gerekli olmayan kişisel bilgilerin istenmemesi esastır. Kullanıcıların da yalnızca talebin değerlendirilmesi için gerekli bilgileri paylaşması önerilir. Özellikle üçüncü kişilere ait kişisel veriler gereksiz şekilde gönderilmemelidir.</p>

<h2>13. Saklama ve İmha</h2>
<p>Veriler, işleme amacı için gerekli süre ve varsa ilgili mevzuatta öngörülen süre boyunca saklanır. Saklama süresi; veri kategorisi, işleme amacı, hukuki yükümlülükler ve olası uyuşmazlıklar dikkate alınarak belirlenmelidir. Süre sona erdiğinde uygulanabilir mevzuata uygun şekilde silme, yok etme veya anonimleştirme işlemleri gerçekleştirilir.</p>

<h2>14. İlgili Kişinin Hakları</h2>
<p>KVKK'nın 11. maddesi kapsamında ilgili kişiler; kişisel verilerinin işlenip işlenmediğini öğrenme, işlenmişse bilgi talep etme, işleme amacını ve amaca uygun kullanılıp kullanılmadığını öğrenme, yurt içinde veya yurt dışında aktarılan üçüncü kişileri bilme, eksik veya yanlış verilerin düzeltilmesini isteme, kanuni şartları oluştuğunda silinmesini veya yok edilmesini isteme, düzeltme/silme/yok etme işlemlerinin aktarılan üçüncü kişilere bildirilmesini isteme, münhasıran otomatik sistemlerle analiz sonucu aleyhe bir sonucun ortaya çıkmasına itiraz etme ve kanuna aykırı işleme nedeniyle zarar doğması halinde zararın giderilmesini talep etme haklarına sahiptir.</p>

<h2>15. Başvuru ve İletişim</h2>
<p>KVKK kapsamındaki talepler, veri sorumlusuna mevzuatta öngörülen başvuru usullerine uygun şekilde iletilmelidir. Bu sitenin gerçek şirket ve başvuru bilgileri yayına alınmadan önce kesinleştirilmelidir. Başvuru kanalı; veri sorumlusunun gerçek e-posta/adres bilgileriyle açıkça gösterilmelidir.</p>

<h2>16. Çocukların Verileri</h2>
<p>Site ve hizmetlerin çocuklara yönelik olup olmadığı, yaş sınırlaması ve çocuklara ait verilerin işlenmesine ilişkin süreçler gerçek hizmet modeline göre belirlenmelidir. Çocuklara ait kişisel verilerin gereksiz şekilde toplanmaması ve özel durumlarda ilgili mevzuatın ayrıca değerlendirilmesi gerekir.</p>

<h2>17. Üçüncü Taraf Bağlantıları</h2>
<p>Site üzerinden üçüncü taraf internet sitelerine veya hizmetlere bağlantı verilmesi halinde, bu sitelerin kendi veri işleme ve çerez uygulamalarından Akıncı Yazılım sorumlu olmayabilir. Kullanıcıların üçüncü taraf sitelerin kendi politikalarını ayrıca incelemesi gerekir.</p>

<h2>18. Güncelleme ve Sürüm Takibi</h2>
<p>Hizmetler, teknik altyapı, kullanılan üçüncü taraf servisler veya mevzuat değiştiğinde bu metin yeniden değerlendirilir. Güncel sürüm tarihi ve önemli değişikliklerin kaydı şirketin kendi uyum sürecinde ayrıca tutulmalıdır.</p>

<p class="legal-foot"><b>Son güncelleme:</b> <?=date('d.m.Y')?> · Bu metin, KVKK Kurumu'nun aydınlatma yükümlülüğü ve ilgili kişi haklarına ilişkin güncel resmi açıklamaları dikkate alınarak hazırlanmış bir taslaktır. Gerçek veri işleme faaliyetleriyle karşılaştırılmadan hukuki uyum garantisi olarak değerlendirilmemelidir.</p>
</section><section id="pane-yasal" class="legal-pane"><h1 class="pane-title">Yasal Zorunluluklar</h1><h1>Yasal Zorunluluklar</h1><p class="lead">Bu bölüm, Akıncı Yazılım'ın internet sitesi ve dijital hizmetleri için yayına almadan önce kontrol edilmesi gereken başlıca hukuki ve operasyonel başlıkları tek yerde toplar.</p><div class="warn"><b>Kontrol listesi hukuki danışmanlık değildir.</b> Şirketin gerçek faaliyet alanı, ticaret sicili, sözleşmeleri, kullandığı servisler, ödeme altyapısı, reklam faaliyetleri, çalışan süreçleri ve veri işleme envanteri görülmeden “tam uyumlu” denilemez.</div>
<div class="req"><div class="num">01</div><div><h2>KVKK aydınlatması</h2><p>Veri sorumlusu kimliği, işleme amaçları, aktarımlar, toplama yöntemi/hukuki sebep ve ilgili kişi hakları açık ve anlaşılır biçimde sunulmalıdır. Aydınlatma, açık rıza metninden ayrı düşünülmelidir.</p></div></div>
<div class="req"><div class="num">02</div><div><h2>Çerezler</h2><p>Kullanılan tüm çerez ve benzeri teknolojiler envanterlenmelidir. Zorunlu olmayan analiz, performans veya pazarlama teknolojileri için somut işleme şartı ve gerekiyorsa aktif açık rıza mekanizması kurulmalıdır.</p></div></div>
<div class="req"><div class="num">03</div><div><h2>Veri güvenliği</h2><p>Yetkisiz erişimi, hukuka aykırı işlemeyi ve veri kaybını önlemek için teknik ve idari tedbirler uygulanmalıdır. Yönetici hesabı, parolalar, yedekler, dosya izinleri ve güncellemeler düzenli kontrol edilmelidir.</p></div></div>
<div class="req"><div class="num">04</div><div><h2>Veri saklama ve imha</h2><p>Her veri kategorisi için amaçla bağlantılı ve gerekli saklama süresi belirlenmeli; süre sonunda silme, yok etme veya anonimleştirme süreçleri işletilmelidir.</p></div></div>
<div class="req"><div class="num">05</div><div><h2>Başvuru ve ilgili kişi süreçleri</h2><p>KVKK başvurularının alınacağı kanal, yetkili kişi, kimlik doğrulama, cevaplama, kayıt ve arşivleme süreci belirlenmelidir.</p></div></div>
<div class="req"><div class="num">06</div><div><h2>Yurt dışına veri aktarımı</h2><p>Bulut, e-posta, CDN, analitik, hata izleme veya başka bir üçüncü taraf hizmetinin verileri yurt dışına çıkarıp çıkarmadığı tespit edilmelidir. Aktarım varsa güncel KVKK şartlarına göre ayrı değerlendirme yapılmalıdır.</p></div></div>
<div class="req"><div class="num">07</div><div><h2>Ticari elektronik ileti</h2><p>SMS, e-posta veya telefon yoluyla ticari ileti gönderilecekse 6563 sayılı Kanun ve ilgili yönetmelik kapsamındaki izin, ret ve ispat süreçleri incelenmeli; uygun durumlarda İleti Yönetim Sistemi (İYS) süreçleri işletilmelidir.</p></div></div>
<div class="req"><div class="num">08</div><div><h2>Mesafeli satış ve tüketici süreçleri</h2><p>Online satış, ücretli dijital ürün, abonelik veya tüketiciye yönelik hizmet sunuluyorsa ön bilgilendirme, mesafeli sözleşme, cayma hakkı, teslimat/ifaya ilişkin hükümler, ücret ve iletişim bilgileri ayrıca değerlendirilmelidir.</p></div></div>
<div class="req"><div class="num">09</div><div><h2>Fikri ve sınai haklar</h2><p>Logo, görsel, yazılım, oyun, metin, müzik, video ve üçüncü taraf içeriklerinin kullanım hakları belgelenmeli; lisans koşulları ve telif bildirimleri saklanmalıdır.</p></div></div>
<div class="req"><div class="num">10</div><div><h2>Oyun ve dijital ürünler</h2><p>LİG BAŞI gibi dijital ürünlerde yaş sınırı, kullanıcı kuralları, hesap/erişim şartları, içerik politikası, ödeme varsa iade/cayma süreçleri, platform mağazası kuralları ve gerektiğinde çocuk kullanıcılar bakımından özel tedbirler ayrıca incelenmelidir.</p></div></div>
<div class="req"><div class="num">11</div><div><h2>Şirket ve iletişim bilgileri</h2><p>Site üzerinde gerçek ticari unvan, adres, iletişim kanalları ve faaliyet için zorunlu olabilecek şirket/vergisel bilgilerin güncel tutulması gerekir. Bu alanlarda örnek veya yer tutucu bilgi bırakılmamalıdır.</p></div></div>
<div class="req"><div class="num">12</div><div><h2>Hukuki metinlerin versiyonlanması</h2><p>KVKK metni, çerez politikası, kullanım koşulları, gizlilik politikası ve varsa satış sözleşmeleri için güncelleme tarihi ve sürüm kaydı tutulması; değişikliklerin operasyonla uyumlu olması önerilir.</p></div></div>
<p class="legal-foot"><b>Son güncelleme:</b> <?=date('d.m.Y')?> · Mevzuat ve Kurul kararları değişebileceğinden yayına almadan önce güncel resmi kaynaklar ve gerektiğinde hukuk danışmanı ile doğrulama yapılmalıdır.</p></section></article></div><script>
document.querySelectorAll('.legal-tab').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.legal-tab').forEach(function(x){x.classList.remove('active')});document.querySelectorAll('.legal-pane').forEach(function(x){x.classList.remove('active')});btn.classList.add('active');document.getElementById('pane-'+btn.dataset.tab).classList.add('active');history.replaceState(null,'','#'+btn.dataset.tab);})});
(function(){var h=location.hash.replace('#','');if(h==='yasal'){document.querySelector('.legal-tab[data-tab="yasal"]').click();}})();
</script></body></html>